name: Bug Report
description: Report a bug or issue with the poker game
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the application are you running?
      placeholder: ex. commit hash or tag
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the application is affected?
      options:
        - Frontend (Vue.js client)
        - Backend (Poker server)
        - Game Logic
        - Socket Communication
        - UI/UX
        - Other
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what happened!
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Console Logs
      description: If applicable, add console logs or error messages
      render: shell

  - type: input
    id: browser
    attributes:
      label: Browser
      description: What browser are you using?
      placeholder: ex. Chrome 91, Safari 14, Firefox 89

  - type: input
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      placeholder: ex. Windows 10, macOS 11, Ubuntu 20.04

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
