name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: poker-server/package-lock.json
    
    - name: Install backend dependencies
      run: |
        cd poker-server
        npm ci
    
    - name: Run backend tests
      run: |
        cd poker-server
        node test-settings.js
        node test-showdown.js

  test-frontend:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install frontend dependencies
      run: npm ci
    
    - name: Build frontend
      run: npm run build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: frontend-build-${{ matrix.node-version }}
        path: dist/

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install dependencies
      run: |
        npm ci
        cd poker-server && npm ci
    
    # Add linting steps when linter is configured
    # - name: Run ESLint
    #   run: npm run lint
    
    # - name: Run Prettier check
    #   run: npm run prettier:check

  integration-test:
    runs-on: ubuntu-latest
    needs: [test-backend, test-frontend]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'npm'
    
    - name: Install all dependencies
      run: |
        npm ci
        cd poker-server && npm ci
    
    - name: Start poker server
      run: |
        cd poker-server
        npm start &
        sleep 5
    
    - name: Build frontend
      run: npm run build
    
    - name: Test server health
      run: |
        curl -f http://localhost:3001/health || exit 1
    
    # Add more integration tests as needed
    
    - name: Stop server
      run: pkill -f "node server.js" || true
